#!/usr/bin/env bash

if [ "$1" = "img" ]; then
    IMAGE=$(realpath "$2")

    # Update Pandora's config file
    sed -i -E 's|image ".*"|image "'"$IMAGE"'"|' ~/.config/pandora/pandora.kdl

    # Use pkill (which exists on NixOS) to close Pandora gracefully
    pkill -INT pandora 2>/dev/null
    sleep 0.5

    # Restart Pandora silently
    pandora > /dev/null 2>&1 & disown

    exit 0
fi

exit 0
